### PR TITLE
Create test of repo permissions

### PR DESCRIPTION
**Pull request by jasongitmail**
CC @barriebyron for testing

### CODE REVIEW

**Comment by barriebyron** [comment]
@jasongitmail did you want to test auto-PR assignment? if so, this PR did not assign reviewers.

**Comment by jasongitmail** [comment]
Looking to test that you are able to approve it and merge it.

**Review by barriebyron — APPROVED** [review]
I see what the GitHub teams did for us here. Note to self: Look under Files changed to see the option to "review changes"

+1

**Comment by jasongitmail** [comment]
Works! Thanks for trying!

**Pull request closed without merging**
