### PR TITLE
Update instructions for running Rosetta node

### PR DESCRIPTION
**Pull request by joaosreis**
This pull request updates the instructions for running a Rosetta node. It includes changes to the docker run command, environment variables, and port numbers. The instructions now provide more details and examples for running the node on different networks.

### CODE REVIEW

**Comment by qwadratic** [comment]
GTG!
@barriebyron can you please merge?

**Review by Trivo25 — APPROVED** [review]

**Comment by joaosreis** [comment]
@Trivo25 this requires an additional authorization on Vercel, as per one of the above bot comments. Could you please check that?

**Comment by Trivo25** [comment]
> @Trivo25 this requires an additional authorization on Vercel, as per one of the above bot comments. Could you please check that?
@joaosreis Yup, this was granted - https://docs2-git-fork-joaosreis-update-rosetta-docs-minadocs.vercel.app/

**Comment by joaosreis** [comment]
Maybe it's because I'm not authorized to merge it. Please feel free to merge it if you can.

**Comment by Trivo25** [comment]
Oh you are right, it somehow didn't work the first time. CI should run now

**Pull request merged**
