### PR TITLE
fix: MF Delegation Program spreadsheet and text revision for MF program

### PR DESCRIPTION
**Pull request by barriebyron**
This PR includes requested changes to the [Mina Foundation Delegation Program](https://docs.minaprotocol.com/node-operators/foundation-delegation-program) doc.

Updated doc preview for your viewing pleasure https://docs2-git-mf-delegation-fix-minadocs.vercel.app/node-operators/foundation-delegation-program

The updated address file is downloaded as .csv from https://docs.google.com/spreadsheets/d/1Fm4XSS9Xu4eWAhpM06sdySUKvLClR5SculXfP5o5sSc/edit#gid=0  to replace the incorrect file at `static/Mina_Foundation_Addresses.csv`

I retained the existing name of the spreadsheet and renamed the downloaded .csv to match the current doc.

The docs style guide is updated with the Markdown syntax for linking to a file:

https://github.com/o1-labs/docs2/wiki/Markdown-Syntax#adding-files-to-docs

### CODE REVIEW

**Comment by duncand0nuts** [comment]
Hi 👋 
We have some updated language for this section: https://github.com/o1-labs/docs2/pull/565

**Comment by barriebyron** [comment]
> Hi 👋 We have some updated language for this section: #565

approved and merged

**Comment by barriebyron** [comment]
@duncand0nuts  indicate approval here and we'll get this merged today!

**Comment by duncand0nuts** [comment]
This is approved from MF side 👍

**Review by MartinMinkov — APPROVED** [review]

**Pull request merged**
