### PR TITLE
Update copyright on the docs footer

### PR DESCRIPTION
**Pull request by halsaphi**
Update to footer to have the correct copyright date.

Adding a getdate function and using it to always have correct copyright date.

### CODE REVIEW

**Review by 45930 — CHANGES_REQUESTED** [review]
I tested this locally and found that even serving the static build results in this js function running on every page load.  It's not a huge impact on performance, but it seems like unnecessary bloat.

Is there a way to get this value to be set at build time, then it will stay up to date over time but not trigger JS in the client?

**Comment by halsaphi** [comment]
I'm not aware of a way to do this in Docusaurus - though I'm no expert, so if you can find a way please let me know - other option is to set it to 2024 - though this would require an update next year.

**Comment by 45930** [comment]
@halsaphi So one thing you can do is export a new constant from `src/constants.ts` and set it to '2024'.  Then either add a ci rule that tests the constant against the current year, or write a prebuild script (just some js that gets run automatically before build) to check the value and re-write the file if it's wrong.

I don't think updating it manually once per year is a bad idea either.

**Comment by halsaphi** [comment]
@45930 - hardcoded the value -> can you merge so docs have correct copyright notice. This will need updating again in a few months.

**Comment by snaitmouloud-mf** [comment]
Hi guys,
can we get this merged please ?
It's 5 days this is open just to change the year.
Thanks.

**Pull request merged**
