### PR TITLE
Docs: Add Token Authorization and Proofs

### PR DESCRIPTION
**Pull request by MartinMinkov**

### CODE REVIEW

**Comment by es92** [comment]
@MartinMinkov @jasongitmail wdyt about the token part being a tutorial, vs just in advanced snarkyjs? Lmk, can move it into a separate tutorial if we're a go. Happy to share more thoughts too if helpful

**Comment by MartinMinkov** [comment]
> @MartinMinkov @jasongitmail wdyt about the token part being a tutorial, vs just in advanced snarkyjs? Lmk, can move it into a separate tutorial if we're a go. Happy to share more thoughts too if helpful

I think tokens are complex enough to warrant a tutorial, I think it's a great idea! What about keeping both a section in `Advanced SnarkyJS` that's high level and then has a call to action with a tutorial with more details?

**Comment by es92** [comment]
Awesome, yeah sounds good! I'll message on slack to align on a plan

**Comment by jasongitmail** [comment]
@MartinMinkov Advanced SnarkyJS has been refactored into a section now. Can you submit a new PR against this page please? https://docs.minaprotocol.com/zkapps/advanced-snarkyjs/custom-tokens Is it ready from your side, to be merged otherwise?

(I'll close this one PR)

**Pull request closed without merging**
